name: Bug Report
description: Create a bug report.
labels:
  - type::bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to make OpenTURNS better!
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What should have happened instead? Please provide as many details as possible. The more information provided, the more likely we are able to replicate your problem and offer a solution.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: How to reproduce the issue?
      description: Please add a minimal script that helps replicating the issue
      render: shell
  - type: textarea
    id: version
    attributes:
      label: OpenTURNS version
      description: |
        Please tell us the OT version you are using.

         ```python
         import openturns as ot
         print(ot.__version__)
         ```
    validations:
      required: true
  - type: dropdown
    id: oscheck
    attributes:
      label: OS
      description: Please provide the operating system.
      options:
        - Windows
        - Linux
        - MacOS
        - All
        - Other
    validations:
      required: true
  - type: checkboxes
    id: sourcecheck
    attributes:
      label: Installation media
      description: Please provide the installation media.
      options:
        - label: pip
        - label: conda
        - label: Windows NSIS installer
        - label: Debian package
        - label: RPM package
        - label: From source
        - label: Other
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Conda Config
      description: |
        Let's collect any customizations you may have for your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda config --show-sources
        ```
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information (or screenshots) that you think would be valuable.
