name: Bug Report
description: Create a bug report.
labels:
  - type::bug
body:
  - type: markdown
    attributes:
      value: |
        Because processing new bug reports is time-consuming, we would like to ask you to fill out the following form to the best of your ability and as completely as possible.

        > **Note**
        > Bug reports that are incomplete or missing information may be closed as inactionable.

        Since there are already a lot of open issues, please also take a moment to search existing ones to see if your bug has already been reported. If you find something related, please upvote that issue and provide additional details as necessary.

        Thank you for helping to make OpenTURNS better!
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all of the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I searched open reports and couldn't find a duplicate
          required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What should have happened instead? Please provide as many details as possible. The more information provided, the more likely we are able to replicate your problem and offer a solution.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: How to reproduce the issue?
      description: Please add a minimal script that helps replicating the issue
      render: shell
  - type: textarea
    id: version
    attributes:
      label: OpenTURNS version
      description: |
        Please tell us the OT version you are using.

         ```python
         import openturns as ot
         print(ot.__version__)
         ```
    validations:
      required: true
  - type: dropdown
    id: oscheck
    attributes:
      label: OS
      description: Please provide the operating system.
      options:
        - Windows
        - Linux
        - MacOS
        - All
        - Other
    validations:
      required: true
  - type: checkboxes
    id: sourcecheck
    attributes:
      label: Installation media
      description: Please provide the installation media.
      options:
        - label: pip
        - label: conda
        - label: Deb
        - label: RPM
        - label: From source
        - label: Other
  - type: textarea
    id: config
    attributes:
      label: Conda Config
      description: |
        Let's collect any customizations you may have for your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda config --show-sources
        ```
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information (or screenshots) that you think would be valuable.
