name: CMake build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: intel, version: '2023.1'}
          - {compiler: intel-classic, version: '2021.9'}
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: sudo apt-get install cmake liblapack-dev libxml2-dev libboost-math-dev libcminpack-dev python3-dev swig libtbb-dev libceres-dev libunwind-dev
      - uses: awvwgk/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - name: Build
        run: |
          ${{ env.FC }} --version
          ${{ env.CC }} --version
          make FC=$FC CC=$CC -C testcase1
          # make FC=$FC CC=$CC -C testcase2
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_Fortran_COMPILER=${{ env.FC }} -DCMAKE_C_FLAGS="-Wall -Wextra" -LAH testcase2
          make
          ./main2
          git clone --depth 1 https://github.com/openturns/openturns.git
          cd openturns
          cmake -DCMAKE_CXX_FLAGS="-Wall" -DCMAKE_C_FLAGS="-Wall" -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 -DCMAKE_INSTALL_PREFIX=$PWD/install .
          make install
          
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}
