name: CMake build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Install
        shell: cmd
        run: |
          conda install -y pip
      - name: Build
        shell: cmd
        run: |
          pip install otmorris
          python -c "import openturns; print(42)"
          echo "ok doki"
          python -c "import otrobopt; print(42)"
          echo "ok doki"
          python -c "import otmorris; print(42)"
          echo "ok doki"

  